name: Generate terraform docs and inframap
on:
  pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Substitua pela sua região          

      - name: Terraform fmt
        run: terraform fmt --recursive

      - name: Terraform Init
        run: terraform init -backend-config=environment/dev/backend.tfvars

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary -var-file=environment/dev/terraform.tfvars

      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Create & commit inframap diagram with PR
        uses: erzz/inframap-action@v1
        with:
          input: tfplan.json
          output: diagram.png
          pr-comment: true