name: Generate terraform docs and inframap
on:
  - pull_request

jobs:
  generate-docs: #Name of the job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Create & commit inframap diagram with PR
        uses: erzz/inframap-action@v1
        with:
          input: tfplan.json
          output: diagram.png
          pr-comment: true
