name: Docs
on: pull_request

jobs:
  diag:
    name: Create inframap diagram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create & commit diagram with PR
        uses: erzz/inframap-action@v1
        with:
          pr-comment: true